### ISSUE TITLE
UsePrivilegeSeparation 'sandbox' breaks on older versions

### ISSUE THREAD

**Issue by fj40crawler** [saltstack-formulas/openssh-formula#108]
The push last night has broken older versions of openssh e.g. openssh on centos6. Ideally UsePrivilegeSeparation 'sandbox' would be conditional based on the version of openssh installed or would be set to a value that works for older, but still vendor supported, versions.

**Comment by aboe76** [comment]
You can also set the pillar data back on the machines that are centos 6.

```
sshd_config:
  UsePrivilegeSeparation: 'yes'
```

**Comment by alxwr** [comment]
I'm opening a PR to fix this issue for CentOS 6.
IMHO we should not compromise on the security of newer systems for the benefit of a few older systems.

**Comment by alxwr** [comment]
Please have a look at #109

**Comment by javierbertoli** [comment]
I think this formula is a good candidate to an overhaul separating yaml files for default, osfamily, osversion, etc. I'll see if I can tackle it these days and push a PR.

**Comment by alxwr** [comment]
@javierbertoli :+1:

**Comment by aboe76** [comment]
@javierbertoli good Idea, let us merge this first if @fj40crawler is ok with the fix from @alxwr

**Comment by fj40crawler** [comment]
This looks like it will work. Note that in issue #102 that this feature is no longer supported (openssh 7). There were a few more deprecated settings as well noted in there. This may not help out with versions that flat out don't have the feature present.
