### ISSUE TITLE
Wishlist: ability to include short hostname entries in known_hosts

### ISSUE THREAD

**Issue by doubletwist13** [saltstack-formulas/openssh-formula#110]
openssh.known_hosts works great, except it only includes the fqdn in the entries.
In our environment we use 'search' in resolv.conf and thus often use short names. 
This does not match the known hosts entry which uses the fqdn, and thus either asks the user to verify the host key or if strict checking is on it blocks the connection altogether. 

It would be nice if there was an option to have the formula generate host-key entries using the short hostname in addition to the fqdn entries it already adds when using openssh.known_hosts.

**Comment by alxwr** [comment]
@doubletwist13 Your wish may be granted (if PR #110) gets merged.

To be honest: I wanted that feature for myself for some time now. :-)

**Comment by aboe76** [comment]
@doubletwist13 can this be closed?

**Comment by doubletwist13** [comment]
Yes. Thank you!
