### ISSUE TITLE
Can changed config files default to Backup?

### ISSUE THREAD

**Issue by grendelson** [saltstack-formulas/openssh-formula#116]
The "backup: minion" setting is not present in the config.sls file.  So someone trying to get this working may inadvertently change an SFTP server or a server with custom settings all to defaults and will not have an easy way to restore.  Salt allows easy backups and restoration without having to go to tape or other method - any change to an existing file seems like it should Default to "backup"

**Comment by hudecof** [comment]
I would like to have an option to backup original file before change.

**Comment by noelmcloughlin** [comment]
The [backup option is supported](https://docs.saltstack.com/en/latest/ref/states/backup_mode.html#file-state-backups) - this issue just needs a PR to implement this.

**Comment by noelmcloughlin** [comment]
I'm wrong!  the backup parameter this issue is requesting is the following?
```
backup -- Create a backup of the original file with the extension: "Year-Month-Day-Hour-Minutes-Seconds".
```
I think that issue on salt.  For this formula you could add `cmd.run` state to take a backup?

**Comment by hudecof** [comment]
@noelmcloughlin adding `backup: minion` for file.managed should be enough, isn't it?

I'm new in salt, so maybe silly question.
I d not want to enable it globally in minion configuration file.

**Comment by noelmcloughlin** [comment]
I guess yes because I do not like messing with global config either. To be honest I never used the `backup:minion` option ... and `backup: True` option is not supported?

 If you open a PR to add `backup:minion` then would fix this issue?
