### ISSUE TITLE
Implement 'Secure Secure Shell' best practices

### ISSUE THREAD

**Issue by eliasp** [saltstack-formulas/openssh-formula#26]
The [Secure Secure Shell](https://stribika.github.io/2015/01/04/secure-secure-shell.html) article outlines some best practices to increase the security of the SSH client and server configuration.

The server part could be implemented in this formula.

It should be enabled by default, but it should be possible to disable or weaken it a bit as AFAIK there are some issues with poor Windows or Android clients which aren't able to keep up with the latest & greatest security standards. I don't have any specific details what options cause trouble on Windows/Android, but this could be implemented incrementally when real-world issues are reported.

**Comment by aboe76** [comment]
@eliasp , you need to make sure that putty still understands this, because the MAC's used I have my doubt if putty (mostly used on windows) can handle it.

**Comment by ingben** [comment]
I think it is worth to support the necessary configuration options explicitly. See PR #41.

A PR to support changing the `/etc/ssh/moduli` file is in the working.

**Comment by gravyboat** [comment]
I've merged #43, @eliasp can you please see if this addresses your concerns?

**Comment by eliasp** [comment]
LGTM.
Thanks a lot for implementhing this.
