### ISSUE TITLE
Feature request: make values in map.jinja onverridable

### ISSUE THREAD

**Issue by fbettag** [saltstack-formulas/openssh-formula#31]
It would be great if one could override values in map.jinja from Pillars.
My use case is that we're using FreeBSD openssh-portable package (because we link it against LibreSSL and it has HPN patches), and it would be great if i could override the service and package in pillars.

Thanks

**Comment by babilen** [comment]
They should already be. You can define the following to override values in the `openssh` map:

```
openssh:
  lookup:
       server: 'openssh-server',
       client: 'openssh-client',
       service: 'ssh',
       sshd_config: '/etc/ssh/sshd_config',
       sshd_config_src: 'salt://openssh/files/sshd_config',
       banner: '/etc/ssh/banner',
       banner_src: 'salt://openssh/files/banner',
       dig_pkg: 'dnsutils',
```

This is, unfortunately, not documented in `pillar.example`, but I don't see a reason why it wouldn't work.

**Comment by fbettag** [comment]
Sorry, i just read it in the docs: Values in the lookup table may be overridden by values in Pillar. 

Thanks!

**Comment by babilen** [comment]
@fbettag You are welcome. Most formulas support (or should!) support the `foo:lookup` mechanism of overriding values in the `map.jinja` lookup table. Please continue to report formulas in which this doesn't work!
