### ISSUE TITLE
Name moduli in sls openssh is not a dictionary

### ISSUE THREAD

**Issue by RichardLaing** [saltstack-formulas/openssh-formula#50]
Hi I am getting the following error on ubuntu 14.04

Name moduli in sls openssh is not a dictionary

I have updated so i am no longer getting the bug of the older salt-maser & minion version so thanks for that.
However I am unsure of how to fix the issue with the moduli section of the pillar.

**Comment by gravyboat** [comment]
Is this the same issue that you commented regarding the fix over here? https://github.com/saltstack-formulas/openssh-formula/issues/42

**Comment by RichardLaing** [comment]
No, that issue was fixed now I am suck with this one

**Comment by gravyboat** [comment]
Have you created your own moduli section that looks like this? https://github.com/saltstack-formulas/openssh-formula/blob/master/pillar.example#L154

**Comment by RichardLaing** [comment]
Hi there I have just start on salt-stack again and I fixed this issue, thank for the help.
