### ISSUE TITLE
Pillar data

### ISSUE THREAD

**Issue by RichardLaing** [saltstack-formulas/openssh-formula#56]
Hi there I was wanting to know if I could get some help with an issue I am having using this formula.

This issue is after installing the formula and adding the folder to my salt masters top file I am able to set the pillar data and can look up the values I have set inside the pillar however these are not being applied to the salt run.

The main example I can give is have set the port over into 10022 however when running a high state the openssh-server still ends up on port 22, I can look up the salt pillar values with the following commands.

salt 'salt-master' pillar.get ssh_config & salt 'salt-master' pillar.get sshd_config

Both of these commands show port 10022 as the port yet this will not take effect, how do I fix the formula so that I will run correctly?

Top file
```
base:
  '*':
    - vim
    - core
    - openssh
```

Pillar top file
```
base:
  '*':
    - openssh

```
Tree view from the base for the salt config.
```

├── core
│   └── init.sls
├── openssh
│   ├── auth.sls
│   ├── banner.sls
│   ├── client.sls
│   ├── config.sls
│   ├── defaults.yaml
│   ├── files
│   │   ├── banner
│   │   ├── fire_banner
│   │   ├── ssh_config
│   │   ├── sshd_config
│   │   └── ssh_known_hosts
│   ├── init.sls
│   ├── known_hosts.sls
│   ├── map.jinja
│   └── moduli.sls
├── pillars
│   ├── openssh
│   │   └── init.sls
│   └── top.sls
├── top.sls
└── vim
    └── init.sls

```

**Comment by enver** [comment]
Can you paste result of ```> salt 'salt-master' pillar.get sshd_config``` ?

**Comment by RichardLaing** [comment]
Sure you can

```
salt-master:
    ----------
    AcceptEnv:
        LANG LC_*
    AuthenticationMethods:
        publickey,keyboard-interactive
    ChallengeResponseAuthentication:
        no
    HostKey:
        - /etc/ssh/ssh_host_rsa_key
        - /etc/ssh/ssh_host_dsa_key
        - /etc/ssh/ssh_host_ecdsa_key
        - /etc/ssh/ssh_host_ed25519_key
    HostbasedAuthentication:
        no
    IgnoreRhosts:
        yes
    KeyRegenerationInterval:
        3600
    LogLevel:
        INFO
    LoginGraceTime:
        120
    PasswordAuthentication:
        no
    PermitEmptyPasswords:
        no
    PermitRootLogin:
        yes
    Port:
        10022
    PrintLastLog:
        yes
    PrintMotd:
        no
    Protocol:
        2
    PubkeyAuthentication:
        yes
    RSAAuthentication:
        yes
    RhostsRSAAuthentication:
        no
    ServerKeyBits:
        1024
    StrictModes:
        yes
    Subsystem:
        sftp /usr/lib/openssh/sftp-server
    SyslogFacility:
        AUTH
    TCPKeepAlive:
        yes
    UseDNS:
        yes
    UsePAM:
        yes
    UsePrivilegeSeparation:
        yes
    X11DisplayOffset:
        10
    X11Forwarding:
        yes
```

**Comment by aboe76** [comment]
@RichardLaing you should use: openssh.config as state instead of openssh

the openssh state (init.sls) only installs the package and start the service

the openssh.config (config.sls) will include openssh(init.sls) state and configures the openssh service.

**Comment by RichardLaing** [comment]
Ah thank you, I was wondering why when I looked into the config that it was looking at the pillar but not using it, oh feel so silly now.

Thank you my good sir, you are awesome.

**Comment by aboe76** [comment]
@RichardLaing no problem sometimes salt states are working in different ways,
some formulas use the base name to install and configure everything some formulas are different.
and let you choose what you want...
