### ISSUE TITLE
ServerKeyBits default in pillar.example is too low

### ISSUE THREAD

**Issue by stooj** [saltstack-formulas/openssh-formula#66]
According to the sshd_config manpage on my Ubuntu and Arch boxes, the minimum and default value for `ServerKeyBits` is 1024.

pillar.example sets it to

```
ServerKeyBits: 768
```

**Comment by babilen** [comment]
The default that is being used is indeed 1024 as you can see in https://github.com/saltstack-formulas/openssh-formula/blob/master/openssh/files/sshd_config#L63 and the `pillar.example` file demonstrates how one can override this default.

I'm not sure whether `pillar.example` must reflect the defaults set in `default.yaml` and `map.jinja` in particular as these could be platform specific.

**Comment by kpostrup** [comment]
I do not think `pillar.example` necessarily should reflect what is in `default.yaml`. In most cases it would make sense for it to deviate from the defaults. On the other hand I think that `pillar.example` should contain example settings that would somewhat make sense in a production environment.

**Comment by babilen** [comment]
I totally agree with you on "should contain example settings that would somewhat make sense in a production environment."

**Comment by ek9** [comment]
I also believe some of the default `KexAlgorithms`, `Ciphers` and `MACs` warrant updating. I have updated the ones in `pillar.example` in PR #81 . I would also suggest to update the defaults in `openssh/files/sshd_config`. The configs in the PR are based on https://stribika.github.io/2015/01/04/secure-secure-shell.html and I believe having those defaults would make this formula produce very secure configuration by default.

**Comment by ek9** [comment]
This can now be closed as #81 got merged, the default value was set to `1024`
