### ISSUE TITLE
any way to define multiple TCP ports?

### ISSUE THREAD

**Issue by daks** [saltstack-formulas/openssh-formula#70]
Hi,

I wonder if there is anyway to define multiple ports for OpenSSH to listen to? I can't find how.
If it's not possible, do you think this option can be added?

Thanks.

**Comment by javierbertoli** [comment]
Set a port's list in your pillar, and it will work. Something like this in `pillars/openssh.sls` will do:
```
sshd_config:
  Port: [ '22', '2222', '3333' ]
```
or 
```
sshd_config:
  Port:
    - 22
    - 2222
    - 3333
```
